### get all resources 
GET http://localhost:8080/api/Bones

### get single resource 
GET http://localhost:8080/api/Bones

### create resource 
POST http://localhost:8080/api/Bones HTTP/1.1
content-type: application/json

{
"BoneCode": "1000","Name": "Unshaven", "Demerits": "1", "PenaltyTours": "1"
}

### update resource 
PUT http://localhost:8080/api/Bones/ content-type: application/json

{
"name": "Joe Smith", "rank": "PVT", "class": "2022"
}

### delete resource 
DELETE http://localhost:8080/api/Bones/